apiVersion: v1
kind: Pod
metadata:
  name: disposable
  namespace: rm
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
    command: ["/bin/sh", "-c", "nginx -g 'daemon off;'"]
