apiVersion: v1
kind: Pod
metadata:
  name: operator
  namespace: apps
spec:
  serviceAccountName: api-access
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
    command: ["/bin/sh", "-c", "nginx -g 'daemon off;'"]
