# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp-education/ubuntu-24-04"
  config.vm.define "control-plane" do |plane|
    plane.vm.hostname = "control-plane"
    plane.vm.network "private_network", ip: "192.168.56.4"
    plane.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end
  end

  (1..2).each do |i|
    config.vm.define "worker-#{i}" do |plane|
      plane.vm.hostname = "worker"
      plane.vm.network "private_network", ip: "192.168.56.#{5+i}"
      plane.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
        vb.cpus = 2
      end
    end
  end
end
